export const text = 'text'
export const link = 'link'
export const image = 'img'
export const gap = 'gap'
export const header = 'header'
export const mainHeader = 'mainHeader'
export const mainImage = 'mainImage'
